### ISSUE TITLE
Develop & Test requirements in cpanfile are not ignored

### ISSUE THREAD

**Issue by djerius** [jhthorsen/app-implode#2]
If `cpanfile` has `develop` or `test` sections, those modules are included.  I expected them to be ignored.  The following cpanfile illustrates this.

```
on runtime => sub {
    requires 'Acme::Xyzzy';
};

on test => sub {
    requires 'Acme::Homer';
};

on develop => sub {
    requires 'Acme::Laugh';
};

```

Here's the output:

```
% \rm -f make-world.im && implode src/make-world  make-world.im
Building application in /tmp/9JwX99me4e
Successfully installed Acme-Laugh-v0.0.5
Successfully installed Acme-Homer-0.0.2
Successfully installed Acme-Xyzzy-0.001
3 distributions installed
Generating make-world.im with embedded bzip archive...
[...]


```

**Comment by jhthorsen** [comment]
"Implode" was mostly an experiment, which I don't really maintain. Do you want to contribute take over?

I tried to clean up and push a new branch "bundle-tar-files", but I wasn't able to figure out the state of the branch.

**Comment by jhthorsen** [comment]
Closing this because of lack of interest.
